include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false

analyzer:
  plugins:
    - drift
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "bricks/**"
    - "**/*.gr.dart"
  errors:
    invalid_annotation_target: ignore