name: embers_fitness
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  bloc: ^8.1.2
  bloc_effects: ^1.0.3
  drift: ^2.14.0
  equatable: ^2.0.5
  fast_immutable_collections: ^9.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.4
  flutter_slidable: ^3.0.1
  freezed_annotation: ^2.4.1
  go_router: ^13.0.1
  intl: ^0.19.0
  json_annotation: ^4.8.1
  path: ^1.8.3
  path_provider: ^2.0.0
  rxdart: ^0.27.7
  sqlite3: ^2.3.0
  sqlite3_flutter_libs: ^0.5.0

dev_dependencies:
  build_runner: ^2.4.7
  drift_dev: ^2.14.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
