name: embers_fitness
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  bloc: ^8.1.2
  drift: ^2.14.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  go_router: ^13.0.1
  intl: ^0.19.0
  path: ^1.8.3
  path_provider: ^2.0.0
  sqlite3: ^2.3.0
  sqlite3_flutter_libs: ^0.5.0

dev_dependencies:
  build_runner: ^2.4.7
  drift_dev: ^2.14.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
